language: cpp

compiler:  
    - gcc
    - clang

before_install:
    - sudo apt-get install libopencv-dev libavcodec-dev libavformat-dev libavutil-dev libswscale-dev libavdevice-dev

before_script:  
    - mkdir build
    - cd build
    - cmake ..

script: make
